name: py5
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.6.*
  - black=22.6.*
  - cairo=1.16.*
  - cairocffi=1.3.*
  - cairosvg=2.5.*
  - cookiecutter=1.7.*
  - flake8=4.0.*
  - ipython=8.3.*
  # remove after jedi bug fix
  - jedi=0.17.2
  - jupyter=1.0.*
  - jupyter-book=0.13.*
  - jupyter-packaging=0.12.*
  - jupyterlab=3.4.*
  - line_profiler=3.4.*
  - matplotlib=3.5.*
  - nodejs=17.8.*
  - numpy=1.22.*
  - pandas=1.4.*
  - pillow=9.1.*
  - pip=22.0.*
  - python=3.8.*
  - requests=2.27.*
  - twine=4.0.*
  - wheel=0.37.*
  - yarn=1.22.*
  - pip:
    - bump2version==1.0.*
    - jpype1==1.3.*
    - rstcheck==5.0.*
    - stackprinter==0.2.*
