name: py5
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.6.*
  - cairo=1.16.*
  - cairocffi=1.2.*
  - cairosvg=2.5.*
  - flake8=4.0.*
  - ipython=8.0.*
  # remove after jedi bug fix
  - jedi=0.17.2
  - jupyter=1.0.*
  - jupyterlab=3.2.*
  - line_profiler=3.3.*
  - matplotlib=3.5.*
  - numpy=1.20.*
  - pandas=1.3.*
  - pillow=8.4.*
  - pip
  - python=3.8.*
  - requests=2.27.*
  - twine=3.7.*
  - wheel=0.37.*
  - xmltodict=0.12.*
  - pip:
    - bump2version==1.0.*
    - jpype1==1.3.*
    - nikola==8.2.*
    - nptyping==1.4.*
    - opencv-contrib-python==4.5.*
    - rstcheck==3.3.*
    - scikit-video==1.1.*
    - stackprinter==0.2.*
