name: py5
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.5.*
  - cairo=1.16.*
  - cairocffi=1.2.*
  - cairosvg=2.5.*
  - flake8=3.8.*
  # remove after jedi bug fix
  - jedi=0.17.2
  - jupyter=1.0.*
  - jupyterlab=3.0.*
  - line_profiler=3.1.*
  - matplotlib=3.3.*
  - noise=1.2.*
  - numpy=1.19.*
  - openjdk=11.0.8
  - pandas=1.2.*
  - pillow=8.1.*
  - pip
  - python=3.8.*
  # pegged because of limitation of snooty language server
  - requests=2.24.0
  - sphinx=3.4.*
  - twine=3.3.*
  - wheel=0.36.*
  - xmltodict=0.12.*
  - pip:
    - jpype1==1.2.*
    - nptyping==1.4.*
    - rstcheck==3.3.*
    - stackprinter==0.2.*
    - nikola==8.1.*
